import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author Henry He
 */
public class ImageDisplay extends javax.swing.JPanel {

    //declare variables
    int x = 1;  //current picture to be shown on screen
    Timer slideshow;    //slideshow timer
    JLabel temp;    //JLabel from Frame to display images
    
    //list to hold picture names (These are what the images must be named in the "pictures" folder)
    String[] list = {"pictures\\Image1.jpg","pictures\\Image2.jpg","pictures\\Image3.jpg","pictures\\Image4.jpg","pictures\\Image5.jpg"};
    
    /**
     * Creates new form ImageDisplay
     */
    public ImageDisplay() {
        initComponents();
        
        //set slideshow timer to update image every 10 seconds
        slideshow = new Timer (10000, new ActionListener(){ 

        @Override
        public void actionPerformed(ActionEvent e) {
            //display image
            displayImage(x, temp);
            //set to show next picture
            x+=1;
            //reset picture count when limit is reached
            if (x >= list.length){
                x = 0;
            }
        }
        
    });
        
    }
    
    /**
     * Henry He
     * Rescales images so they are able to fit within the slideshow window and displays it
     * 
     * @param i the picture to rescale in the list
     * @param pic the JLabel to display the picture on
     */
    public void displayImage(int i,JLabel pic){
        
        //create new image from the list for scaling
        ImageIcon icon = new ImageIcon(list[i]);
        Image img = icon.getImage();
        
        //scale the image and convert back to an ImageIcon
        Image scaledImg = img.getScaledInstance(910, 575, Image.SCALE_SMOOTH);
        ImageIcon newImc = new ImageIcon(scaledImg);
        
        //set the JLabel to the current ImageIcon
        pic.setIcon(newImc);
    }
    
    /**
     * Henry He
     * Start the slideshow
     * @param pic the JLabel to display the picture on
     */
    public void startSlideShow(JLabel pic){
        slideshow.start();  //start the slideshow timer
        displayImage(0,pic );   //display a starting image
        temp = pic; //pass the JLabel from the frame into the panel
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
