
import com.teknikindustries.yahooweather.WeatherDisplay;
import com.teknikindustries.yahooweather.WeatherDoc;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author night
 */
public class weather extends javax.swing.JPanel {

    Timer t1 = new Timer(60000, (ActionListener) new TimerListener());

    WeatherDoc doc = new WeatherDoc("4113", "c"); //Your weather API location and units system

    WeatherDisplay disp = new WeatherDisplay(); //Create WeatherDisplay object

    String temp, tempU, conditions, wChill;
    Image weatherBackground = Toolkit.getDefaultToolkit().getImage("space25.jpg");
    Image mixedRainAndSnow = Toolkit.getDefaultToolkit().getImage("weatherIcons\\mixed rain and snow.png");
    Image partlyCloudy = Toolkit.getDefaultToolkit().getImage("weatherIcons\\partly cloudy.png");
    

    Font font;

    /**
     * Creates new form weather
     */
    public weather() {
        initComponents();
    }

    public void start() {
        t1.start();
        getWeather();
        repaint();
    }

    private class TimerListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            getWeather();
            repaint();
        }
    }

    private void getWeather() {
        temp = disp.getTemperature();
        tempU = disp.getTemperatureUnit();
        conditions = disp.getCondition();
        wChill = disp.getWindChill();
    }

    private void showWeather(Graphics g) {
        font = new Font("Calisto MT", Font.PLAIN, 15);
        g.setFont(font);
        g.setColor(Color.white);

        g.drawString(" Conditions: " + conditions, 0, 290);
        g.drawString(" Tempurture: " + temp + " " + tempU, 0, 310);
        g.drawString(" Wind chill: " + wChill + " " + tempU, 0, 330);

    }

    public void paintComponent(Graphics g) {
        g.drawImage(weatherBackground, 0, 0, this);
        g.drawImage(partlyCloudy, -15, -125, this);
        showWeather(g);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
